
# PCA vs. SVD for Dimensionality Reduction & Image Compression


In [7]:

from pca import PCA  # Replace with actual import if in another file

import numpy as np

X = np.array([[1, 2, 3], [2, 4, 1], [3, 8, 0], [4, 6, 5], [5, 10, 2]])
pca = PCA(n_components=2)
X_transformed = pca.fit_transform(X)
X_reconstructed = pca.inverse_transform(X_transformed)

print("Transformed Data:\n", X_transformed)
print("Reconstructed Data:\n", X_reconstructed)


Transformed Data:
 [[ 4.53583794  0.13374158]
 [ 2.05317872 -1.44708723]
 [-2.10036671 -2.09353228]
 [-0.03333961  2.97288526]
 [-4.45531035  0.43399268]]
Reconstructed Data:
 [[ 1.18748961  1.90539029  2.93531631]
 [ 1.69189964  4.15547147  1.10629425]
 [ 3.18216235  7.9080785  -0.06284579]
 [ 3.97524608  6.01249115  5.00854007]
 [ 4.96320233 10.01856859  2.01269515]]


As we can see, it's not perfect, but it does a pretty good job of capturing most of the data


---

## Singular Value Decomposition (SVD) for Image Compression

**Purpose:**  
Compress images by approximating them using fewer singular values.

### Process
1. **Convert Image to Grayscale** (if necessary).
2. **Apply SVD:** `A ≈ U_k * S_k * V_k`
3. **Retain Top `k` Components:** Balance quality vs. compression.
4. **Reconstruct Image:** Use reduced matrices to approximate original.
5. **Compression Ratio:** Estimate space saved.


In [ ]:

from svd_image_compression import SVDImageCompressor 

compressor = SVDImageCompressor(k=50)
compressor.compress('your_image.jpg', 'compressed_image.jpg')
print("Compression Ratio:", compressor.get_compression_ratio('your_image.jpg'))


Compression Ratio: 53.83301184899421
